#!/usr/bin/env python
"""
Build configuration script.
"""
from dev.build import Crate, Link, Linker, Project, Rust
from pathlib import Path

root = Path(__file__).parent


class Target:
    def __init__(self, name: str, triple: str):
        self.name = name
        self.triple = triple


    def add(self, project: Project):
        rust = project.add(Rust(
            self.name,
            target=self.triple,
            flags=[
                '-Cpanic=abort'
            ],
        ))

        self.libcore = rust.add(Crate(
            'core',
            'library/core/src/lib.rs',
            builtin=True,
            sysroot=True,
            path=self.name,
        ))

        rust.add(Crate(
            'compiler_builtins',
            'lib/compiler_builtins/lib.rs',
            builtin=True,
            path=self.name,
            depends=[self.libcore],
        ))

        self.libnucleus = rust.add(Crate(
            'nucleus',
            'sys/nucleus/main.rs',
            path=self.name,
        ))


rv64 = Target('rv64', 'riscv64gc-unknown-none-elf')

with Project(root, root / 'build') as project:
    linker = project.add(Linker('lld'))
    for target in (
        rv64,
    ):
        target.add(project)

    linker.add(Link(
        'platform/riscv/virt/nucleus',
        rv64.libnucleus,
        "sys/platform/riscv/virt.ld",
    ))
