use std::process::ExitCode;

mod ninja;

fn main() -> ExitCode {
    let sysroot = std::process::Command::new("rustc").arg("--print=sysroot").output().unwrap();
    let sysroot = str::from_utf8(&sysroot.stdout).unwrap().trim_end();

    let target = "rv64";

    let mut args = std::env::args_os();
    let program = args.next().unwrap_or_else(|| "setup".into());
    let ninja_path = std::path::PathBuf::from(args.next().unwrap_or_else(|| "build.ninja".into()));
    let ninja_file = format!(r#"# Generated by `{}`; do not edit
subninja setup.ninja

rustflags = --color=always
crates = --extern=core=build/{target}/libcore.rlib --extern=compiler_builtins=build/{target}/libcompiler_builtins.rlib
crate-type = rlib
edition = 2024

rule rustc
    command = rustc $flags $rustflags -Zunstable-options --target=build/{target}/{target}.json --edition=$edition -Clinker-flavor=ld.lld --crate-name=$crate-name --crate-type=$crate-type --emit=link=$out $crates $in
    description = RUST $out
    depfile = $crate-name.d
    deps = gcc

rule cp
    command = cp $in $out

build build/{target}/{target}.json: cp {target}.json

build build/{target}/libcore.rlib: rustc {sysroot}/lib/rustlib/src/rust/library/core/src/lib.rs | {target}.json rust-toolchain.toml
    crate-name = core
    crates =

build build/{target}/libcompiler_builtins.rlib: rustc lib/compiler_builtins/lib.rs | {target}.json rust-toolchain.toml build/{target}/libcore.rlib
    crate-name = compiler_builtins
    crates = --extern=core=build/{target}/libcore.rlib
    flags = --cfg='feature="compiler_builtins"'

build build/{target}/nucleus: rustc sys/nucleus/lib.rs | build/{target}/libcore.rlib build/{target}/libcompiler_builtins.rlib
    crate-type = bin
    crate-name = nucleus
"#, program.display());
    std::fs::write(ninja_path, ninja_file).unwrap();
    ExitCode::SUCCESS
}
