[package]
name = "bluemetal"
version = "0.1.0"
edition = "2024"
license = "MIT"

[[bin]]
name = "bluemetal"
test = false

[features]

[dependencies]
init = { path = "../init" }
serial = { path = "../serial" }
system = { path = "../system" }

[target.'cfg(any(target_arch = "riscv32", target_arch = "riscv64"))'.dependencies]
riscv = { path = "../riscv" }

[build-dependencies]
configure = { path = "../../configure/build" }
