use std::collections::HashMap;
use std::process::ExitCode;
use std::ffi::OsString;
use std::io::Write;

#[derive(Default)]
struct Config<'a> {
    program: OsString,
    sysroot: String,
    plan: Plan<'a>,
}

fn main() -> ExitCode {
    let mut args = std::env::args_os();
    let mut config = Config::default();

    config.program = args.next().unwrap_or_else(|| "setup".into());

    let Some(rule_path) = args.next() else {
        eprintln!("invalid usage: path to `Build` is required");
        return ExitCode::FAILURE;
    };

    let Some(ninja_path) = args.next() else {
        eprintln!("invalid usage: path to `build.ninja` is required");
        return ExitCode::FAILURE;
    };

    let None = args.next() else {
        eprintln!("invalid usage: unexpected argument");
        return ExitCode::FAILURE;
    };

    if config.sysroot.is_empty() {
        match std::process::Command::new("rustc").arg("--print=sysroot").output() {
            Err(error) => {
                eprintln!("failed to determine Rust sysroot: {error}");
                return ExitCode::FAILURE;
            },
            Ok(output) => {
                if !output.status.success() {
                    eprintln!("failed to determine Rust sysroot: rustc returned {}", output.status);
                    return ExitCode::FAILURE;
                }
                let Ok(sysroot) = String::from_utf8(output.stdout) else {
                    eprintln!("failed to determine Rust sysroot: path is not UTF-8");
                    return ExitCode::FAILURE;
                };
                config.sysroot = sysroot.trim_end().into();
            },
        }
    }

    let plan = match std::fs::read_to_string(&rule_path) {
        Ok(plan) => plan,
        Err(error) => {
            eprintln!("failed to read {rule_path:?}: {error}");
            return ExitCode::FAILURE;
        }
    };
    if let Err(error) = config.plan.parse(&plan) {
        eprintln!("failed to parse {rule_path:?}: {error}");
        return ExitCode::FAILURE;
    }

    let ninja_file = match std::fs::File::create(&ninja_path) {
        Ok(f) => f,
        Err(error) => {
            eprintln!("failed to open {ninja_path:?}: {error}");
            return ExitCode::FAILURE;
        },
    };
    let mut writer = std::io::BufWriter::new(ninja_file);
    if let Err(error) = generate(&mut writer, &config) {
        eprintln!("failed to generate {ninja_path:?}: {error}");
        return ExitCode::FAILURE;
    };
    if let Err(error) = writer.flush() {
        eprintln!("failed to write {ninja_path:?}: {error}");
        return ExitCode::FAILURE;
    };
    std::mem::drop(writer);

    ExitCode::SUCCESS
}

fn generate(f: &mut dyn std::io::Write, config: &Config) -> std::io::Result<()> {
    let rust_src = format!("{}/lib/rustlib/src/rust", config.sysroot);

    writeln!(f, "# Generated by {:?}
subninja setup.ninja

edition = 2024
rustflags = --color=always -Dwarnings
", config.program)?;

    ninja::Rule {
        name: "rust",
        command: &["rustc", "$rustflags", "$flags", "--target=$target", "--edition=$edition", "--emit=dep-info=$depfile", "--emit=link=$out", "$in"],
        depfile: Some("$out.d"),
    }.write(f)?;

    let platforms = [
        ("riscv64", "riscv64gc-unknown-none-elf"),
    ];

    let mut crate_names = config.plan.crates.keys().map(|v| *v).collect::<Vec<_>>();
    crate_names.sort();

    for (platform, target) in platforms {
        writeln!(f, "\n# Build Rules for {platform}")?;

        let path = format!("build/{platform}");

        // Crates in the sysroot are done externally
        ninja::Build {
            rule: "rust",
            outputs: &[&format!("{path}/libcore.rlib")],
            inputs: &[&format!("{rust_src}/library/core/src/lib.rs")],
            implicit: &[],
            variables: &[
                ("target", &[target]),
                ("flags", &["--crate-type=lib", "--crate-name=core"]),
            ],
        }.write(f)?;

        for &k in &crate_names {
            let c = &config.plan.crates[k];
            let crate_type = format!("--crate-type={}", c.crate_type);
            let crate_name = format!("--crate-name={}", c.name);
            let mut externs = Vec::new();
            let mut implicit = Vec::new();
            for e in &c.externs {
                externs.push(format!("--extern=core={path}/lib{e}.rlib"));
                implicit.push(format!("{path}/lib{e}.rlib"));
            }
            if c.builtins {
                externs.push(format!("--extern=core={path}/libcore.rlib"));
                implicit.push(format!("{path}/libcore.rlib"));
                externs.push(format!("--extern=compiler_builtins={path}/libcompiler_builtins.rlib"));
                implicit.push(format!("{path}/libcompiler_builtins.rlib"));
            }
            let mut flags = vec![
                crate_type.as_str(),
                crate_name.as_str(),
            ];
            for e in &externs {
                flags.push(e);
            }
            let implicit = implicit.iter().map::<&str, _>(|s| s).collect::<Vec<_>>();
            ninja::Build {
                rule: "rust",
                outputs: &[&format!("{path}/{}", c.output())],
                inputs: &[&c.path()],
                implicit: &implicit,
                variables: &[
                    ("target", &[target]),
                    ("flags", &flags),
                ],
            }.write(f)?;
        }
    }

    Ok(())
}

enum CrateType {
    Lib,
    Bin,
}
impl core::fmt::Display for CrateType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Lib => write!(f, "rlib"),
            Self::Bin => write!(f, "bin"),
        }
    }
}

struct Crate<'a> {
    name: &'a str,
    crate_type: CrateType,
    builtins: bool,
    externs: Vec<&'a str>,
}
impl<'a> Crate<'a> {
    pub fn new(name: &'a str, crate_type: CrateType) -> Self {
        Self {
            name,
            crate_type,
            builtins: true,
            externs: Vec::new(),
        }
    }
    pub fn path(&self) -> String {
        let filename = match self.crate_type {
            CrateType::Lib => "lib.rs",
            CrateType::Bin => "main.rs",
        };
        format!("src/{name}/{filename}", name=self.name)
    }
    pub fn output(&self) -> String {
        match self.crate_type {
            CrateType::Lib => format!("lib{}.rlib", self.name),
            CrateType::Bin => self.name.into(),
        }
    }
    pub fn parse_option(&mut self, rule: &'a str) -> Result<(), &'static str> {
        let mut bits = rule.split(' ');
        let key = bits.next().unwrap();
        let Some(value) = bits.next() else {
            return Err("option is missing a value");
        };
        match (key, value) {
            ("crate-type", "bin") => self.crate_type = CrateType::Bin,
            ("crate-type", "lib") => self.crate_type = CrateType::Lib,
            ("disable", "builtins") => self.builtins = false,
            ("extern", name) => self.externs.push(name),
            _ => return Err("unknown option"),
        }
        if let Some(_) = bits.next() {
            return Err("unexpected value in option");
        }
        Ok(())
    }
}

pub struct PlanError<'a> {
    #[allow(dead_code)]
    plan: &'a str,
    reason: &'static str,
    line: usize,
}
impl core::fmt::Display for PlanError<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        writeln!(f, "invalid statement on line {}: {}", self.line + 1, self.reason)
    }
}

struct Plan<'a> {
    crates: HashMap<&'a str, Crate<'a>>,
}
impl<'a> Plan<'a> {
    pub fn parse(&mut self, plan: &'a str) -> Result<(), PlanError<'a>> {
        let mut lines = plan.lines().enumerate().peekable();
        while let Some((line, s)) = lines.next() {
            if s.ends_with(' ') {
                return Err(PlanError { plan, reason: "trailing whitespace", line });
            }
            if s.is_empty() || s.starts_with('#') {
                continue;
            }
            if s.starts_with("    ") {
                return Err(PlanError { plan, reason: "unexpected indentation, not a within a rule", line });
            }
            if s.starts_with(' ') {
                return Err(PlanError { plan, reason: "invalid indentation size", line });
            }
            let mut bits = s.split(' ');
            match bits.next().unwrap() {
                "crate" => {
                    let Some(name) = bits.next() else {
                        return Err(PlanError { plan, reason: "missing crate name", line });
                    };
                    if bits.next().is_some() {
                        return Err(PlanError { plan, reason: "unexpected value after crate name", line });
                    }
                    let mut c = Crate::new(name, CrateType::Lib);
                    while let Some(&(line, option)) = lines.peek() {
                        if !option.starts_with("    ") {
                            break;
                        }
                        let _ = lines.next();
                        if s.ends_with(' ') {
                            return Err(PlanError { plan, reason: "trailing whitespace", line });
                        }
                        if let Err(reason) = c.parse_option(&option[4..]) {
                            return Err(PlanError { plan, reason, line });
                        }
                    }
                    self.crates.insert(name, c);
                },
                _ => {
                    return Err(PlanError { plan, reason: "unknown rule kind", line });
                },
            }
        }
        Ok(())
    }
}
impl Default for Plan<'_> {
    fn default() -> Self {
        Self {
            crates: HashMap::new(),
        }
    }
}

mod ninja {

    pub struct Rule<'a> {
        pub name: &'a str,
        pub command: &'a [&'a str],
        pub depfile: Option<&'a str>,
    }
    impl Rule<'_> {
        pub fn write(&self, f: &mut dyn std::io::Write) -> std::io::Result<()> {
            write!(f, "rule {}\n  command =", self.name)?;
            for arg in self.command {
                write!(f, " {}", arg)?;
            }
            writeln!(f)?;
            writeln!(f, "  description = {} $out", self.name)?;
            if let Some(depfile) = self.depfile {
                writeln!(f, "  deps = gcc\n  depfile = {depfile}")?;
            }
            Ok(())
        }
    }

    #[derive(Debug)]
    pub struct Build<'a> {
        pub rule: &'a str,
        pub outputs: &'a [&'a str],
        pub inputs: &'a [&'a str],
        pub implicit: &'a [&'a str],
        pub variables: &'a [(&'a str, &'a [&'a str])],
    }
    impl Build<'_> {
        pub fn write(&self, f: &mut dyn std::io::Write) -> std::io::Result<()> {
            write!(f, "build")?;
            for output in self.outputs {
                write!(f, " {}", output)?;
            }
            write!(f, ": {}", self.rule)?;
            for input in self.inputs {
                write!(f, " {}", input)?;
            }
            if !self.implicit.is_empty() {
                write!(f, " |")?;
            }
            for implicit in self.implicit {
                write!(f, " {}", implicit)?;
            }
            writeln!(f)?;
            for &(k, v) in self.variables {
                write!(f, "  {k} =")?;
                for value in v {
                    write!(f, " {value}")?;
                }
                writeln!(f)?;
            }
            writeln!(f)?;
            Ok(())
        }
    }
}
