[package]
name = "configure"
version = "0.0.0"
edition = "2021"

[lib]
path = "src/fix-build-dep-bug.rs"
test = false

[features]
fix-build-dep-bug = ["dep:cc"]

[dependencies]
cc = { version = "1.0.90", optional = true }
