[build]
target = "crates/configure/target/riscv64gc-unknown-bluemetal-elf.json"

[target.riscv64gc-unknown-bluemetal-elf]
runner = ['qemu-system-riscv64', '-s', '-machine', 'sifive_u', '-m', '128M', '-display', 'none', '-serial', 'stdio', '-bios']

[unstable]
unstable-options = true
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem", "panic-unwind"]
