[package]
name = "panic"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
test = false

[dependencies]
serial = { path = "../serial" }

[build-dependencies]
configure = { path = "../../configure/build" }
